version: "3.9"
services:
  # elasticsearch:
  #   image: elasticsearch:7.14.1
  #   expose:
  #     - 9200
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   # volumes:
  #   #   - "./elasticsearch/data:/usr/share/elasticsearch/data"
  #   environment:
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   networks:
  #     - botnet

  fluent-bit:
    image: fluent/fluent-bit:1.8
    # command: "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf"
    ports:
      - "24225:24224/tcp"
      - "24225:24224/udp"
      - "2021:2020"
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
    environment:
      IMAGE_NAME: "twitch-bot-config"
      ES_INDEX: "twitch-bot-config"
    # logging:
    #   driver: "fluentd"
    #   options:
    #     tag: "twitch-bot-config/fluent-bit"
    #     fluentd-address: "localhost:24224"
    #     # fluentd-async: "true"
    # depends_on:
    #   - elasticsearch
    networks:
      - botnet

  # kibana:
  #   image: kibana:7.14.1
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: "http://elasticseach:9200"
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   networks:
  #     - botnet

  # jaeger:
  #   image: "jaegertracing/all-in-one:1.26"
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "14250:14250"
  #     - "9411:9411"
  #   environment:
  #     COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
  #   networks:
  #     - botnet

  redis:
    image: redis
    logging:
      driver: "fluentd"
      options:
        tag: "twitch-bot-config/redis"
        fluentd-address: "localhost:24225"
        # fluentd-async: "true"
    depends_on:
      - fluent-bit
    networks:
      - botnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_DB=0
    ports:
      - "8081:8081"
    depends_on:
      - "redis"
    networks:
      - botnet

  bot-config:
    build: .
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_URI=redis
      # - REDIS_PASSWORD
    volumes:
      - ./etc:/config
      - ./logs:/logs
    logging:
      driver: "fluentd"
      options:
        tag: "twitch-bot-config/bot-config"
        fluentd-address: "localhost:24225"
        # fluentd-async: "true"
    depends_on:
      - "redis"
      - "fluent-bit"
      - "jaeger"
    networks:
      - botnet

networks:
  botnet:
