version: "3.9"
services:
  fluent-bit:
    image: fluent/fluent-bit:1.8
    ports:
      - "24225:24224/tcp"
      - "24225:24224/udp"
      - "2022:2021"
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
    environment:
      IMAGE_NAME: "twitch-bot-config"
      ES_INDEX: "twitch-bot-config"
    networks:
      - botnet

  redis:
    image: redis
    ports:
      - "6379:6379"
      - "9121:9121"
    healthcheck:
      test: [ "CMD-SHELL", "/bin/bash -c \"[[ $$(redis-cli ping) == 'PONG' ]] && echo 0 || echo 1\"" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "fluentd"
      options:
        tag: "twitch-bot-config/redis"
        fluentd-address: "localhost:24225"
    depends_on:
      - fluent-bit
    networks:
      - botnet

  redis-exporter:
    image: oliver006/redis_exporter
    command:
      - "--redis.addr"
      - "--debug"
    environment:
      - REDIS_ADDR=local:redis:6379
      - REDIS_EXPORTER_LOG_FORMAT=json
      - REDIS_EXPORTER_DEBUG=true
    ports:
      - "9122:9121"
    depends_on:
      - redis
    networks:
      - botnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_DB=0
    ports:
      - "8081:8081"
    depends_on:
      - "redis"
    networks:
      - botnet

  bot-config:
    build: .
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_URI=redis
      # - REDIS_PASSWORD
    volumes:
      - ./etc:/config
      - ./logs:/logs
    logging:
      driver: "fluentd"
      options:
        tag: "twitch-bot-config/bot-config"
        fluentd-address: "localhost:24225"
    depends_on:
      - "redis"
      - "fluent-bit"
    networks:
      - botnet

networks:
  botnet:
